# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e32ae410d13edaa93e294c070faac4f575c1463ba893c9f9fcf31897f7f40433ad3f86cbb848c2f316c0aba557f2b0d80aceaeab3139e71c8d1d5fcc1b65a30

test:
  secret_key_base: ec8f3a07bceea5321207ad2e36839c979d0e07ed3efae1aa9a131878f9eef9fef45b1697cf11a243511773fe3860a0add643e0c8d011db348f4e0774ec9ac3a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
